// Seed data for first-time initialization
import { PROJECTS } from '@/config/projects';
import { useProjectStore } from '@/store/useProjectStore';
import { useTaskStore } from '@/store/useTaskStore';
import { useMilestoneStore } from '@/store/useMilestoneStore';
import { useDocumentStore } from '@/store/useDocumentStore';
import { useTodoStore } from '@/store/useTodoStore';
import { useRiskStore } from '@/store/useRiskStore';
import { useResourceStore } from '@/store/useResourceStore';
import { useMemberStore } from '@/store/useMemberStore';

const now = new Date().toISOString();
const today = new Date();
const todayISO = today.toISOString().split('T')[0];
const tomorrow = new Date(today);
tomorrow.setDate(tomorrow.getDate() + 1);
const tomorrowISO = tomorrow.toISOString().split('T')[0];
const nextWeek = new Date(today);
nextWeek.setDate(nextWeek.getDate() + 7);
const nextWeekISO = nextWeek.toISOString().split('T')[0];

export const SEED_DATA = {
  projects: [
    { ...PROJECTS.proj_mom },
    { ...PROJECTS.proj_erp },
  ],

  tasks: [
    // MOM Project Tasks
    {
      id: 'task_mom_1',
      projectId: 'proj_mom',
      title: '生产计划模块需求调研',
      description: '收集各车间生产计划管理现状，梳理功能需求清单',
      assignee: '王工',
      priority: 'high',
      status: 'done',
      startDate: '2026-07-01',
      dueDate: '2026-07-20',
      completedAt: '2026-07-18T00:00:00Z',
      tags: ['需求调研', '生产计划'],
      order: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'task_mom_2',
      projectId: 'proj_mom',
      title: 'MES 数据采集接口开发',
      description: '开发设备数据采集接口，对接车间 PLC 和传感器',
      assignee: '李工',
      priority: 'urgent',
      status: 'in_progress',
      startDate: '2026-07-15',
      dueDate: '2026-08-20',
      completedAt: null,
      tags: ['接口开发', '数据采集'],
      order: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'task_mom_3',
      projectId: 'proj_mom',
      title: '质量管控模块设计',
      description: '完成质量管控模块详细设计，包括检验标准管理和不合格品处理流程',
      assignee: '张工',
      priority: 'high',
      status: 'in_progress',
      startDate: '2026-08-01',
      dueDate: '2026-08-25',
      completedAt: null,
      tags: ['详细设计', '质量管理'],
      order: 1,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'task_mom_4',
      projectId: 'proj_mom',
      title: '设备管理模块开发',
      description: '开发设备台账、点检计划、维修工单等核心功能',
      assignee: '赵工',
      priority: 'medium',
      status: 'todo',
      startDate: '2026-08-15',
      dueDate: '2026-09-30',
      completedAt: null,
      tags: ['模块开发', '设备管理'],
      order: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'task_mom_5',
      projectId: 'proj_mom',
      title: '仓储管理模块联调',
      description: '与 WMS 系统进行数据联调，确保库存数据一致性',
      assignee: '陈工',
      priority: 'medium',
      status: 'review',
      startDate: '2026-07-20',
      dueDate: '2026-08-10',
      completedAt: null,
      tags: ['联调测试', '仓储管理'],
      order: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'task_mom_6',
      projectId: 'proj_mom',
      title: '生产排程算法优化',
      description: '优化 APS 排程算法，考虑设备产能和物料约束',
      assignee: '周工',
      priority: 'high',
      status: 'todo',
      startDate: '2026-09-01',
      dueDate: '2026-10-15',
      completedAt: null,
      tags: ['算法优化', '生产排程'],
      order: 1,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'task_mom_7',
      projectId: 'proj_mom',
      title: '用户培训与操作手册编写',
      description: '编写各模块操作手册，组织关键用户培训',
      assignee: '孙工',
      priority: 'low',
      status: 'todo',
      startDate: '2026-10-01',
      dueDate: '2026-11-15',
      completedAt: null,
      tags: ['培训', '文档'],
      order: 2,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'task_mom_8',
      projectId: 'proj_mom',
      title: '二期上线验收',
      description: '组织二期模块的 UAT 测试和上线验收',
      assignee: '信息化总监',
      priority: 'urgent',
      status: 'blocked',
      startDate: '2026-11-01',
      dueDate: '2026-12-15',
      completedAt: null,
      tags: ['验收', '上线'],
      order: 0,
      createdAt: now,
      updatedAt: now,
    },

    // ERP Project Tasks
    {
      id: 'task_erp_1',
      projectId: 'proj_erp',
      title: '财务模块升级方案评审',
      description: '评审用友 BIP 财务模块升级方案，确认科目映射和报表适配',
      assignee: '信息化总监',
      priority: 'high',
      status: 'done',
      startDate: '2026-05-01',
      dueDate: '2026-05-20',
      completedAt: '2026-05-18T00:00:00Z',
      tags: ['方案评审', '财务模块'],
      order: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'task_erp_2',
      projectId: 'proj_erp',
      title: '供应链模块数据迁移',
      description: '完成采购、库存、销售模块历史数据清洗和迁移',
      assignee: '吴工',
      priority: 'urgent',
      status: 'in_progress',
      startDate: '2026-07-15',
      dueDate: '2026-08-30',
      completedAt: null,
      tags: ['数据迁移', '供应链'],
      order: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'task_erp_3',
      projectId: 'proj_erp',
      title: '生产成本核算模块配置',
      description: '配置 BIP 生产成本核算规则，对接 MOM 工时和物料消耗数据',
      assignee: '郑工',
      priority: 'high',
      status: 'in_progress',
      startDate: '2026-08-01',
      dueDate: '2026-09-15',
      completedAt: null,
      tags: ['成本核算', '模块配置'],
      order: 1,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'task_erp_4',
      projectId: 'proj_erp',
      title: '报表平台改造',
      description: '将现有自定义报表迁移至 BIP 报表平台',
      assignee: '刘工',
      priority: 'medium',
      status: 'todo',
      startDate: '2026-09-01',
      dueDate: '2026-10-30',
      completedAt: null,
      tags: ['报表', '平台迁移'],
      order: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'task_erp_5',
      projectId: 'proj_erp',
      title: 'BIP 与 MOM 接口规范确认',
      description: '确认 BIP 与 MOM 系统间的数据交换接口规范和调用频率',
      assignee: '王工',
      priority: 'high',
      status: 'review',
      startDate: '2026-07-20',
      dueDate: nextWeekISO,
      completedAt: null,
      tags: ['接口规范', '系统对接'],
      order: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'task_erp_6',
      projectId: 'proj_erp',
      title: '用户权限迁移',
      description: '梳理现有用户权限体系，在 BIP 中重新配置角色和权限',
      assignee: '孙工',
      priority: 'medium',
      status: 'todo',
      startDate: '2026-09-15',
      dueDate: '2026-10-31',
      completedAt: null,
      tags: ['权限管理', '用户配置'],
      order: 1,
      createdAt: now,
      updatedAt: now,
    },
  ],

  milestones: [
    // MOM Milestones
    {
      id: 'ms_mom_1',
      projectId: 'proj_mom',
      title: 'MOM 一期上线',
      description: '生产计划与过程管控模块完成部署上线',
      date: '2026-06-30',
      status: 'achieved',
      isCritical: true,
      deliverables: '系统上线运行，完成用户验收',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'ms_mom_2',
      projectId: 'proj_mom',
      title: '二期需求确认',
      description: '完成二期模块需求规格说明书评审',
      date: '2026-07-25',
      status: 'achieved',
      isCritical: true,
      deliverables: '需求规格说明书 v2.0 评审通过',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'ms_mom_3',
      projectId: 'proj_mom',
      title: '二期开发完成',
      description: '质量管控、设备管理、仓储管理模块开发完成',
      date: '2026-10-31',
      status: 'upcoming',
      isCritical: true,
      deliverables: '三个模块通过单元测试和集成测试',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'ms_mom_4',
      projectId: 'proj_mom',
      title: '全量上线交付',
      description: 'MOM 系统全量模块上线，完成终验',
      date: '2026-12-31',
      status: 'at_risk',
      isCritical: true,
      deliverables: '系统终验报告，用户签字确认',
      createdAt: now,
      updatedAt: now,
    },

    // ERP Milestones
    {
      id: 'ms_erp_1',
      projectId: 'proj_erp',
      title: '升级方案评审通过',
      description: 'BIP 升级总体方案通过评审',
      date: '2026-05-20',
      status: 'achieved',
      isCritical: true,
      deliverables: '升级方案评审纪要',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'ms_erp_2',
      projectId: 'proj_erp',
      title: '数据迁移完成',
      description: '所有模块历史数据迁移完成并验证',
      date: '2026-09-15',
      status: 'upcoming',
      isCritical: true,
      deliverables: '数据迁移验证报告',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'ms_erp_3',
      projectId: 'proj_erp',
      title: '系统切换上线',
      description: 'BIP 系统切换上线，旧系统停用',
      date: '2026-11-30',
      status: 'upcoming',
      isCritical: true,
      deliverables: '上线切换报告，旧系统归档',
      createdAt: now,
      updatedAt: now,
    },
  ],

  documents: [
    {
      id: 'doc_mom_1',
      projectId: 'proj_mom',
      title: 'MOM 系统需求规格说明书 v2.0',
      category: '需求文档',
      description: '二期模块（质量管控、设备管理、仓储管理）需求规格说明',
      fileName: 'MOM需求规格说明书v2.0.docx',
      fileSize: '2.3MB',
      tags: ['需求', '二期'],
      uploadDate: '2026-08-01',
      location: 'PLM 系统文档库 / MOM 项目 / 需求文档',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc_mom_2',
      projectId: 'proj_mom',
      title: 'MOM 系统架构设计文档',
      category: '设计文档',
      description: '系统总体架构设计，包括微服务划分、数据库设计和接口规范',
      fileName: 'MOM架构设计文档.docx',
      fileSize: '1.8MB',
      tags: ['架构设计', '微服务'],
      uploadDate: '2026-06-15',
      location: 'PLM 系统文档库 / MOM 项目 / 设计文档',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc_mom_3',
      projectId: 'proj_mom',
      title: 'MOM 一期验收报告',
      category: '验收报告',
      description: '一期模块（生产计划、过程管控）验收报告',
      fileName: 'MOM一期验收报告.pdf',
      fileSize: '950KB',
      tags: ['验收', '一期'],
      uploadDate: '2026-07-05',
      location: 'PLM 系统文档库 / MOM 项目 / 验收报告',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc_erp_1',
      projectId: 'proj_erp',
      title: 'BIP 升级方案评审纪要',
      category: '会议纪要',
      description: '用友 BIP 升级方案评审会议纪要，包含评审结论和后续行动计划',
      fileName: 'BIP升级方案评审纪要.docx',
      fileSize: '320KB',
      tags: ['评审', '方案'],
      uploadDate: '2026-05-22',
      location: 'PLM 系统文档库 / ERP 升级 / 会议纪要',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc_erp_2',
      projectId: 'proj_erp',
      title: '数据迁移方案',
      category: '计划报告',
      description: '供应链模块数据迁移方案，包含数据清洗规则和迁移步骤',
      fileName: '数据迁移方案.docx',
      fileSize: '1.2MB',
      tags: ['数据迁移', '供应链'],
      uploadDate: '2026-07-10',
      location: 'PLM 系统文档库 / ERP 升级 / 计划报告',
      createdAt: now,
      updatedAt: now,
    },
  ],

  todos: [
    {
      id: 'todo_1',
      title: '审批 MOM 二期开发计划',
      description: '需要在今日完成审批并反馈给开发团队',
      dueDate: todayISO,
      priority: 'urgent',
      completed: false,
      completedAt: null,
      projectId: 'proj_mom',
      remindAt: `${todayISO}T09:00:00`,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'todo_2',
      title: '确认 ERP 数据迁移范围',
      description: '与各业务部门确认历史数据迁移范围和截止时间',
      dueDate: todayISO,
      priority: 'high',
      completed: false,
      completedAt: null,
      projectId: 'proj_erp',
      remindAt: `${todayISO}T14:00:00`,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'todo_3',
      title: '审核 MOM-ERP 接口规范文档',
      description: '审核接口规范文档，重点关注数据一致性和异常处理',
      dueDate: tomorrowISO,
      priority: 'high',
      completed: false,
      completedAt: null,
      projectId: 'proj_mom',
      remindAt: `${tomorrowISO}T09:00:00`,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'todo_4',
      title: '组织 MOM 用户培训排期',
      description: '协调各车间关键用户，确定培训时间和场次',
      dueDate: nextWeekISO,
      priority: 'medium',
      completed: false,
      completedAt: null,
      projectId: 'proj_mom',
      remindAt: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'todo_5',
      title: '整理信息化工作月报',
      description: '汇总 MOM 和 ERP 项目进展，编写信息化工作月报',
      dueDate: nextWeekISO,
      priority: 'medium',
      completed: false,
      completedAt: null,
      projectId: null,
      remindAt: null,
      createdAt: now,
      updatedAt: now,
    },
  ],

  risks: [
    {
      id: 'risk_mom_1',
      projectId: 'proj_mom',
      title: 'MOM 与 ERP 接口对接延迟风险',
      description: 'ERP 升级时间不确定，可能导致 MOM 接口适配工作无法按期启动',
      severity: 'high',
      probability: 'medium',
      status: 'open',
      impact: 'schedule',
      mitigation: '提前与 ERP 团队确认接口规范，并行开发适配层',
      owner: '信息化总监',
      identifiedDate: '2026-07-15',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'risk_mom_2',
      projectId: 'proj_mom',
      title: '生产排程算法精度不达标',
      description: 'APS 排程算法在复杂约束下可能无法达到预期精度',
      severity: 'medium',
      probability: 'medium',
      status: 'mitigating',
      impact: 'quality',
      mitigation: '引入外部算法顾问，增加算法验证测试覆盖',
      owner: '周工',
      identifiedDate: '2026-07-20',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'risk_mom_3',
      projectId: 'proj_mom',
      title: '用户接受度风险',
      description: '车间操作人员对新系统接受度不确定，可能影响上线效果',
      severity: 'medium',
      probability: 'high',
      status: 'open',
      impact: 'scope',
      mitigation: '提前组织关键用户参与需求评审，制定培训计划',
      owner: '孙工',
      identifiedDate: '2026-06-01',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'risk_erp_1',
      projectId: 'proj_erp',
      title: '历史数据迁移完整性风险',
      description: '用友旧系统到 BIP 的数据迁移可能存在丢失或不一致',
      severity: 'critical',
      probability: 'medium',
      status: 'mitigating',
      impact: 'quality',
      mitigation: '建立数据校验规则，执行多轮迁移测试',
      owner: '吴工',
      identifiedDate: '2026-07-01',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'risk_erp_2',
      projectId: 'proj_erp',
      title: '业务中断风险',
      description: '系统切换期间可能导致业务短暂中断',
      severity: 'high',
      probability: 'low',
      status: 'open',
      impact: 'schedule',
      mitigation: '制定分模块切换计划，选择业务低谷期执行切换',
      owner: '信息化总监',
      identifiedDate: '2026-07-10',
      createdAt: now,
      updatedAt: now,
    },
  ],

  resources: [
    {
      id: 'res_mom_1',
      projectId: 'proj_mom',
      name: '后端开发组',
      role: '后端开发',
      allocation: 80,
      availability: 'full',
      skills: ['Java', 'Spring Boot', 'PostgreSQL', 'Redis'],
      notes: '负责 MOM 核心服务开发，含 MES 接口和排程引擎',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'res_mom_2',
      projectId: 'proj_mom',
      name: '前端开发组',
      role: '前端开发',
      allocation: 60,
      availability: 'shared',
      skills: ['React', 'TypeScript', 'Ant Design'],
      notes: 'MOM 与 ERP 前端共用，当前以 MOM 为主',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'res_mom_3',
      projectId: 'proj_mom',
      name: '赛意实施顾问团队',
      role: '实施顾问',
      allocation: 40,
      availability: 'partial',
      skills: ['MOM', 'MES', '半导体行业'],
      notes: '赛意 MOM 原厂实施团队，每周驻场 2 天',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'res_erp_1',
      projectId: 'proj_erp',
      name: '用友实施团队',
      role: 'ERP 实施',
      allocation: 70,
      availability: 'full',
      skills: ['用友 BIP', '财务', '供应链'],
      notes: '负责 BIP 模块配置和数据迁移指导',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'res_erp_2',
      projectId: 'proj_erp',
      name: '数据迁移专项组',
      role: '数据工程',
      allocation: 100,
      availability: 'full',
      skills: ['SQL', '数据清洗', 'ETL'],
      notes: '专职负责历史数据清洗和迁移验证',
      createdAt: now,
      updatedAt: now,
    },
  ],

  members: [
    {
      id: 'mem_1',
      name: '信息化总监',
      role: 'admin',
      department: '信息化中心',
      title: '信息化总监',
      email: 'cio@example.com',
      phone: '',
      projectIds: ['proj_mom', 'proj_erp'],
      avatarColor: '#ef4444',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'mem_2',
      name: '王工',
      role: 'pm',
      department: '信息化中心',
      title: 'MOM 项目经理',
      email: 'wang@example.com',
      phone: '',
      projectIds: ['proj_mom'],
      avatarColor: '#3b82f6',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'mem_3',
      name: '吴工',
      role: 'pm',
      department: '信息化中心',
      title: 'ERP 项目经理',
      email: 'wu@example.com',
      phone: '',
      projectIds: ['proj_erp'],
      avatarColor: '#14b8a6',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'mem_4',
      name: '李工',
      role: 'member',
      department: '开发部',
      title: '后端开发工程师',
      email: 'li@example.com',
      phone: '',
      projectIds: ['proj_mom'],
      avatarColor: '#8b5cf6',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'mem_5',
      name: '张工',
      role: 'member',
      department: '开发部',
      title: '系统设计工程师',
      email: 'zhang@example.com',
      phone: '',
      projectIds: ['proj_mom'],
      avatarColor: '#f59e0b',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'mem_6',
      name: '郑工',
      role: 'member',
      department: '财务部',
      title: '成本核算专员',
      email: 'zheng@example.com',
      phone: '',
      projectIds: ['proj_erp'],
      avatarColor: '#ec4899',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'mem_7',
      name: '赵工',
      role: 'member',
      department: '开发部',
      title: '前端开发工程师',
      email: 'zhao@example.com',
      phone: '',
      projectIds: ['proj_mom', 'proj_erp'],
      avatarColor: '#06b6d4',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'mem_8',
      name: '孙工',
      role: 'viewer',
      department: '生产部',
      title: '关键用户',
      email: 'sun@example.com',
      phone: '',
      projectIds: ['proj_mom'],
      avatarColor: '#84cc16',
      createdAt: now,
      updatedAt: now,
    },
  ],
};

// Inject seed data through Zustand stores after hydration
export function initSeedData() {
  const inject = async () => {
    // 注意：不再自动推送种子数据到后端，避免 Vite HMR 反复触发导致重复推送
    // 种子数据仅作为 localStorage 离线兜底使用

    const setIfEmpty = (store, key, data) => {
      const current = store.getState()[key];
      if (!current || current.length === 0) {
        store.setState({ [key]: data });
      }
    };

    setIfEmpty(useProjectStore, 'projects', SEED_DATA.projects);
    setIfEmpty(useTaskStore, 'tasks', SEED_DATA.tasks);
    setIfEmpty(useMilestoneStore, 'milestones', SEED_DATA.milestones);
    setIfEmpty(useDocumentStore, 'documents', SEED_DATA.documents);
    setIfEmpty(useTodoStore, 'todos', SEED_DATA.todos);
    setIfEmpty(useRiskStore, 'risks', SEED_DATA.risks);
    setIfEmpty(useResourceStore, 'resources', SEED_DATA.resources);

    // 注入种子成员数据：仅当成员列表完全为空时兜底注入，
    // 避免「个别成员缺 password」触发整盘覆盖，导致后端真实成员被种子假数据替换。
    const currentMembers = useMemberStore.getState().members;
    const membersEmpty = !currentMembers || currentMembers.length === 0;

    if (membersEmpty) {
      useMemberStore.setState({ members: SEED_DATA.members });
    }

    localStorage.setItem('pw_initialized', 'true');
  };

  if (useProjectStore.persist.hasHydrated()) {
    inject();
  } else {
    useProjectStore.persist.onFinishHydration(inject);
  }
}
